export const SAVED_ADD_ITEM = "SAVED_ADD_ITEM";
export const SAVED_REMOVE_ITEM = "SAVED_REMOVE_ITEM";
export const SAVED_CLEAR_ITEMS = "SAVED_CLEAR_ITEMS";
export const SAVED_UPDATE_ITEMS = "SAVED_UPDATE_ITEMS";